Repository requests-cache/aiohttp-client-cache, pull requests merged in 2021-04, with the labels that each got.

#41 Documentation & CI updates
  .github/workflows/build.yml
  .readthedocs.yml
  CONTRIBUTING.md
  README.md
  aiohttp_client_cache/backends/base.py
  docker-compose.yml
  docs/Dockerfile
  docs/conf.py
  docs/index.rst
  setup.py
Labels: docs

#43 Add optional integration with itsdangerous
  .github/workflows/build.yml
  HISTORY.md
  LICENSE
  MANIFEST.in
  README.md
  aiohttp_client_cache/backends/__init__.py
  aiohttp_client_cache/backends/base.py
  aiohttp_client_cache/backends/dynamodb.py
  aiohttp_client_cache/backends/gridfs.py
  aiohttp_client_cache/backends/mongo.py
  aiohttp_client_cache/backends/redis.py
  aiohttp_client_cache/backends/sqlite.py
  docker-compose.yml
  docs/conf.py
  setup.cfg
  setup.py
  test/conftest.py
  test/integration/__init__.py
  test/integration/test_cache.py
  test/unit/test_base_backend.py
Labels: enhancement, tests

#37 async impl of DynamoDBBackend
  .github/workflows/build.yml
  README.md
  aiohttp_client_cache/backends/dynamodb.py
  setup.py
  test/integration/test_dynamodb_backend.py
Labels: enhancement

#49 Add support for per-request expiration
  CONTRIBUTING.md
  HISTORY.md
  aiohttp_client_cache/backends/base.py
  aiohttp_client_cache/backends/mongo.py
  aiohttp_client_cache/cache_keys.py
  aiohttp_client_cache/expiration.py
  aiohttp_client_cache/response.py
  aiohttp_client_cache/session.py
  pyproject.toml
  test/integration/test_cache.py
  test/integration/test_mongo_backend.py
  test/integration/test_redis_backend.py
  test/integration/test_sqlite_backend.py
  test/unit/test_base_backend.py
  test/unit/test_expiration.py
  test/unit/test_response.py
Labels: enhancement
