Repository requests-cache/aiohttp-client-cache, pull requests merged in 2023-10, with the labels that each got.

#183 Take disabled status of CachedSession for CacheActions
  aiohttp_client_cache/backends/base.py
  aiohttp_client_cache/cache_control.py
  aiohttp_client_cache/session.py
  test/integration/base_backend_test.py
Labels: bug

#179 Unit test fixes for FileBackend.
  aiohttp_client_cache/backends/filesystem.py
  test/integration/base_backend_test.py
  test/integration/test_filesystem.py
Labels: tests

#186 Further unit test fixes
  test/integration/base_storage_test.py
  test/integration/test_redis.py
  test/integration/test_sqlite.py
Labels: bug, tests

#192 Add attribute `closed` to `CachedResponse`
  aiohttp_client_cache/response.py
  test/unit/test_response.py
Labels: bug

#189 Close SQLite connection if session is deleted and thread is still running
  aiohttp_client_cache/backends/sqlite.py
  noxfile.py
  poetry.lock
  pyproject.toml
  test/integration/base_backend_test.py
  test/integration/test_memory.py
  test/integration/test_sqlite.py
  test/unit/test_base_backend.py
Labels: bug, enhancement

#188 Support for conditional requests
  aiohttp_client_cache/backends/base.py
  aiohttp_client_cache/cache_control.py
  aiohttp_client_cache/session.py
  examples/github.py
  test/integration/base_backend_test.py
Labels: enhancement

#194 Handle responses that exceed DynamoDB max item size
  .pre-commit-config.yaml
  HISTORY.md
  aiohttp_client_cache/backends/dynamodb.py
  poetry.lock
  test/integration/test_dynamodb.py
Labels: bug, enhancement
